
#pragma once

#define PRINTALL 0x80
#define IMPORTEDFUNCTIONS 0x1
#define IMPORTEDFUNCTIONLIST 0x2
#define IMPORTEDLIBRARIES 0x4
#define IMPORTEDLIBRARIELIST 0x8
#define EXPORTEDFUNCTIONS 0x10
#define EXPORTEDFUNCTIONLIST 0x20